### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-rachio-platform:

### ISSUE THREAD

**Issue by burtamcgna** [kcharwood/homebridge-rachio-platform#7]
Getting the following error when starting the homebridge service on a MAC.  Have configured the external IP/Port forwarding as indicated in the instructions.  Wondering if it is a specific JS version or NPM version issue?

ERROR LOADING PLUGIN homebridge-rachio-platform:
[4/20/2019, 10:16:04 PM] /usr/local/lib/node_modules/homebridge-rachio-platform/index.js:115
    async refreshDevices() {
          ^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

**Comment by thevangogh** [comment]
Hi there,
I have the same issue. The router port mapping needs the home bridge container to start before the port mapping can work. The plugin container won't start if the router mapping is not working. It's chicken and egg issue.

Can we please remove the port validation when initialising the plugin?

**Comment by NickChristensen** [comment]
Based on your stack trace, it looks like you're using a version of Node that doesn't support async/await. If you're still stuck on this, try upgrading to Node 8+.
